[project]
name = "danser-www-19"
version = "0.1.0"
description = ""
authors = [
    {name = "BK",email = "sdsf1225@gmail.com"}
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
tensorflow = ">=2.8, <=2.12"
numpy = "*"
pandas = "*"
scikit-learn = "<1.6.0"
tqdm = "^4.67.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
