[project]
name = "graphrec-www19"
version = "0.1.0"
description = ""
authors = [
    {name = "BK",email = "sdsf1225@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch ",
    "numpy ",
    "pandas ",
    "scikit-learn "
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
